//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_ÖDEV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbürünEntities : DbContext
    {
        public DbürünEntities()
            : base("name=DbürünEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_katagori> Tbl_katagori { get; set; }
        public virtual DbSet<Tbl_musteri> Tbl_musteri { get; set; }
        public virtual DbSet<Tbl_satıs> Tbl_satıs { get; set; }
        public virtual DbSet<Tbl_urun> Tbl_urun { get; set; }
    }
}
